# .github/pr-labeler.yml
# The bot always updates the labels, add/remove as necessary [default: false]
alwaysReplace: false
# Treats the text and labels as case-sensitive [default: true]
caseSensitive: true
# Array of labels to be applied to the PR [default: []]
customLabels:
  # Finds the `text` within the PR title and body and applies the `label`
  - text: 'hotfix:'
    label: 'hotfix'
  - text: 'test:'
    label: 'test'
  - text: 'feature'
    label: 'feature'
  - text: 'feat:'
    label: 'feature'
  - text: 'enhancement'
    label: 'enhancement'
  - text: 'fix:'
    label: 'bug'
  - text: 'docs:'
    label: 'documentation'
  - text: 'build:'
    label: 'build'
  - text: 'ci:'
    label: 'ci'
  - text: 'style:'
    label: 'style'
  - text: 'refactor:'
    label: 'refactor'
  - text: 'perf:'
    label: 'performance'
  - text: 'chore:'
    label: 'chore'
  - text: 'revert:'
    label: 'revert'
  - text: 'release'
    label: 'release'
  - text: 'i18n'
    label: 'i18n'
  - text: 'breaking'
    label: 'breaking'
# Search the body of the PR for the `text` [default: true]
searchBody: false
# Search the title of the PR for the `text` [default: true]
searchTitle: true
# Search for whole words only [default: false]
wholeWords: false
