name: "Lint PR"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          ignoreLabels: |
            hotfix
            dependencies
            release
          types: |
            feat
            enhancement
            fix
            hotfix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
            i18n
